"""P4-D: `rilavo init --framework <nextjs|fastapi|express|go|wordpress>` scaffolding.

Emits the exact middleware integration files proven in Phases 1-2 of the
packaging plan (rilavo-next's createMiddleware, rilavo.fastapi's
require_rilavo_agent, and an Express adapter over @rilavo/sdk's
verifyCredential). Templates are static strings locked by golden-file tests;
the generator only writes files and never executes them.
"""
from __future__ import annotations

import json
from pathlib import Path

# ============================================================================
# NEXT.JS MIDDLEWARE TEMPLATE
# ============================================================================
NEXTJS_MIDDLEWARE_TS = """// Generated by `rilavo init --framework nextjs`.
// Fail-closed Rilavo gate for Next.js (P2-A). Requires:
//   npm install @rilavo/sdk @rilavo/next
import { createMiddleware } from '@rilavo/next';

const withRilavo = createMiddleware({
  audience: 'YOUR_AUDIENCE_HERE',
  publicPaths: ['/', '/public/:path*'],
  // Wire issuerDirectory / revocationLog to your trust sources here.
});

export default withRilavo;

export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon.ico).*)'],
};
"""

# ============================================================================
# FASTAPI TEMPLATE
# ============================================================================
FASTAPI_MAIN_PY = """# Generated by `rilavo init --framework fastapi`.
# Fail-closed Rilavo gate for FastAPI (P2-B2). Requires:
#   pip install fastapi uvicorn  (rilavo already installed)
from fastapi import Depends, FastAPI

from rilavo.fastapi import require_rilavo_agent
from rilavo.keys import IssuerKeyEntry, KeyDirectory

app = FastAPI()

# Trust source: point this at your issuer directory (static here; swap in
# DiscoveringKeyDirectory for .well-known/rilavo discovery).
directory = KeyDirectory()
directory.publish(IssuerKeyEntry(
    fingerprint_id="rilavo:iss:YOUR_ISSUER_ID",
    public_key_pem=open("issuer_public_key.pem", "rb").read(),
    valid_until=9999999999.0,
))

# Gate order matches verifier.py exactly:
# version -> expiry -> audience -> delegation -> signature -> PoP.
agent = require_rilavo_agent(
    audience="YOUR_AUDIENCE_HERE",
    key_directory=directory,
)


@app.get("/protected")
async def protected(result: dict = Depends(agent)):
    # Raises HTTPException 401 with reason_code on failure.
    return {"message": "Access granted", "principal": result.principal}
"""

# ============================================================================
# EXPRESS TEMPLATE
# ============================================================================
EXPRESS_GATE_JS = """// Generated by `rilavo init --framework express`.
// Fail-closed Rilavo gate for Express/Connect (P2-B3). Requires:
//   npm install @rilavo/sdk
const { verifyCredential, NonceCache } = require('@rilavo/sdk');

const HEADER = 'x-rilavo-credential';
const AUDIENCE = 'YOUR_AUDIENCE_HERE';

// Trust source: configure with your issuer directory and revocation log.
const issuerDirectory = {
  unreachable: false,
  lookup(issuerId) {
    // TODO: Implement issuer directory lookup.
    // Must resolve issuerId to {issuerId: string, publicKeyPem: string, validUntil: int}.
    // Options: static in-memory map, filesystem, HTTP discovery (RILAVO_ISSUER_DIR_URL),
    // or external key management service. Return null on unknown/not found (fail-closed).
    return null;
  },
};
const revocationLog = { isRevoked: () => false };
const nonceCache = new NonceCache();   // process-wide replay cache

function rilavoGate(req, res, next) {
  const raw = req.get(HEADER);
  if (!raw) return res.status(401).json({ error: 'no_credentials' });

  let fields;
  try {
    fields = JSON.parse(Buffer.from(raw, 'base64').toString('utf8'));
  } catch {
    return res.status(401).json({ error: 'malformed_credential' });
  }

  const result = verifyCredential(
    fields,
    {
      method: req.method,
      path: req.path,
      requestedAction: req.get('x-rilavo-action') || '',
      signature: req.get('x-rilavo-pop-signature') || '',
      requestNonce: req.get('x-rilavo-request-nonce') || '',
    },
    {
      issuerDirectory,
      revocationLog,
      nonceCache,
      verifierAudience: AUDIENCE,
    },
  );

  if (!result.accepted) {
    return res.status(401).json({ error: result.reasonCode });
  }
  req.rilavo = result;
  next();
}

module.exports = { rilavoGate };
"""

# ============================================================================
# GO TEMPLATE
# ============================================================================
GO_MAIN = """// Generated by `rilavo init --framework go`.
// Fail-closed Rilavo gate for Go net/http (P2-B4). Requires:
//   go get github.com/rilavo/rilavo-go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/rilavo/rilavo-go"
)

func main() {
	// Trust source: configure with your issuer directory and revocation log.
	directory := rilavo.NewKeyDirectory()
	// directory.Publish(...)  // Add your issuer key entry

	revLog := &rilavo.RevocationLog{}
	nonceCache := rilavo.NewNonceCache()

	verifier := rilavo.NewVerifier(directory, revLog, nonceCache)

	// Middleware
	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		fmt.Fprintln(w, `{"message": "Access granted"}`)
	})

	// Wrap with Rilavo gate
	gated := rilavo.Middleware(verifier, "YOUR_AUDIENCE_HERE")(handler)

	http.Handle("/protected", gated)
	http.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintln(w, `{"status": "ok"}`)
	})

	log.Fatal(http.ListenAndServe(":8080", nil))
}
"""

GO_GO_MOD = """module YOUR_MODULE_NAME

go 1.22

require github.com/rilavo/rilavo-go v0.1.0
"""

# ============================================================================
# WORDPRESS TEMPLATE
# ============================================================================
WP_PLUGIN = """<?php
/**
 * Plugin Name: Rilavo Agent Verification
 * Description: Fail-closed Rilavo gate for WordPress (P2-B5).
 * Version: 0.1.0
 * Author: Rilavo Contributors
 * License: Apache-2.0
 * Requires at least: 5.9
 * Requires PHP: 8.1
 * Text Domain: rilavo-verification
 */

// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit;
}

// Require the Rilavo SDK (assumes composer install in plugin dir)
require_once __DIR__ . '/vendor/autoload.php';

use Rilavo\\Verifier;
use Rilavo\\KeyDirectory;
use Rilavo\\RevocationLog;
use Rilavo\\NonceCache;

class Rilavo_Verification {

    private $verifier;
    private $audience;

    public function __construct() {
        $this->audience = get_option('rilavo_audience', 'YOUR_AUDIENCE_HERE');

        // Initialize trust sources
        $directory = new KeyDirectory();
        // $directory->publish(...) // Add your issuer key entry

        $revocationLog = new RevocationLog();
        $nonceCache = new NonceCache();

        $this->verifier = new Verifier($directory, $revocationLog, $nonceCache);

        // Hook into WordPress
        add_action('init', [$this, 'register_hooks']);
        add_action('admin_menu', [$this, 'admin_menu']);
        add_action('admin_init', [$this, 'register_settings']);

        // REST API gate
        add_filter('rest_pre_dispatch', [$this, 'gate_rest_request'], 10, 3);
        // Admin gate (optional)
        // add_action('admin_init', [$this, 'gate_admin_request']);
    }

    public function register_hooks() {
        // Register AJAX endpoints for PoP
        add_action('wp_ajax_nopriv_rilavo_pop', [$this, 'pop_endpoint']);
    }

    public function admin_menu() {
        add_options_page(
            'Rilavo Verification',
            'Rilavo Verification',
            'manage_options',
            'rilavo-verification',
            [$this, 'settings_page']
        );
    }

    public function register_settings() {
        register_setting('rilavo_options', 'rilavo_audience');
        register_setting('rilavo_options', 'rilavo_issuer_key');
    }

    public function settings_page() {
        ?>
        <div class="wrap">
            <h1>Rilavo Verification Settings</h1>
            <form method="post" action="options.php">
                <?php settings_fields('rilavo_options'); ?>
                <table class="form-table">
                    <tr>
                        <th scope="row">Audience</th>
                        <td><input type="text" name="rilavo_audience" value="<?php echo esc_attr(get_option('rilavo_audience')); ?>" class="regular-text"></td>
                    </tr>
                    <tr>
                        <th scope="row">Issuer Public Key (PEM)</th>
                        <td><textarea name="rilavo_issuer_key" class="large-text code"><?php echo esc_textarea(get_option('rilavo_issuer_key')); ?></textarea></td>
                    </tr>
                </table>
                <?php submit_button(); ?>
            </form>
        </div>
        <?php
    }

    public function gate_rest_request($dispatch_result, $request, $route) {
        // Skip non-REST or public routes
        if (is_wp_error($dispatch_result) || $this->is_public_route($request)) {
            return $dispatch_result;
        }

        // Get credential from header
        $cred_header = $request->get_header('X-Rilavo-Credential');
        if (!$cred_header) {
            return new WP_Error('no_credentials', 'Missing credential', ['status' => 401]);
        }

        // Decode credential
        $fields = json_decode(base64_decode($cred_header), true);
        if (!$fields) {
            return new WP_Error('malformed_credential', 'Invalid credential encoding', ['status' => 401]);
        }

        // Build PoP request
        $pop = [
            'method' => $request->get_method(),
            'path' => $request->get_route(),
            'requestedAction' => $request->get_header('X-Rilavo-Action') ?? '',
            'signature' => $request->get_header('X-Rilavo-Pop-Signature') ?? '',
            'requestNonce' => $request->get_header('X-Rilavo-Request-Nonce') ?? '',
        ];

        try {
            $result = $this->verifier->verify($fields, $pop, [
                'issuerDirectory' => $directory,
                'revocationLog' => $revocationLog,
                'nonceCache' => $nonceCache,
                'verifierAudience' => $this->audience,
            ]);
        } catch (Exception $e) {
            return new WP_Error('verification_failed', $e->getMessage(), ['status' => 401]);
        }

        if (!$result['accepted']) {
            return new WP_Error($result['reasonCode'], 'Verification failed', ['status' => 401]);
        }

        return $dispatch_result;
    }

    private function is_public_route($request) {
        $public = ['/wp-json/wp/v2/', '/wp-json/oembed/'];
        $route = $request->get_route();
        foreach ($public as $p) {
            if (strpos($route, $p) === 0) return true;
        }
        return false;
    }
}

// Initialize
new Rilavo_Verification();
"""

WP_COMPOSER = """{
    "name": "rilavo/verification",
    "description": "Rilavo Agent Verification for WordPress",
    "type": "wordpress-plugin",
    "license": "Apache-2.0",
    "require": {
        "php": ">=8.1",
        "rilavo/sdk": "^0.1"
    },
    "require-dev": {
        "phpunit/phpunit": "^10.0",
        "squizlabs/php_codesniffer": "^3.7"
    },
    "autoload": {
        "psr-4": {
            "Rilavo\\": "src/"
        }
    },
    "scripts": {
        "test": "phpunit",
        "cs-check": "phpcs --standard=WordPress src/",
        "cs-fix": "phpcbf --standard=WordPress src/"
    }
}
"""

# ============================================================================
# DOCKERFILE TEMPLATE (shared)
# ============================================================================
DOCKERFILE = """# Generated by `rilavo init --framework {framework}`
# Multi-stage build for production
FROM {base_image} AS builder

WORKDIR /app

# Install dependencies
{install_deps}

# Copy source
COPY . .

# Build if needed
{build_cmd}

# Production stage
FROM {base_image} AS production

WORKDIR /app

# Copy only production artifacts
{copy_artifacts}

# Non-root user
USER 1000:1000

EXPOSE {port}

CMD ["{cmd}"]
"""

# ============================================================================
# README TEMPLATE
# ============================================================================
README = """# {project_name}

Rilavo-protected {framework} application.

## Quick Start

1. Configure your issuer and audience in the source code
2. Install dependencies: `{install_cmd}`
3. Run: `{run_cmd}`

## Configuration

| Variable | Description | Default |
|----------|-------------|---------|
| `AUDIENCE` | Your verifier identifier | `YOUR_AUDIENCE_HERE` |
| `ISSUER_KEY` | Issuer public key (PEM) | `issuer_public_key.pem` |

## Development

```bash
{dev_cmd}
```

## Production

```bash
docker build -t {project_name} .
docker run -p {port}:{port} {project_name}
```

## Rilavo Integration

This application uses Rilavo for agent authorization verification.
See [Rilavo Documentation](https://docs.rilavo.org) for details.
"""

# ============================================================================
# GITHUB ACTIONS CI TEMPLATE
# ============================================================================
GITHUB_CI = """# Generated by `rilavo init --framework {framework}`
name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up {setup_name}
        uses: actions/setup-{setup_id}@v4
        with:
          {setup_version}: '{setup_version}'
          cache: '{cache}'
      - name: Install dependencies
        run: {install_cmd}
      - name: Run tests
        run: {test_cmd}
      - name: Lint
        run: {lint_cmd}
"""

# ============================================================================
# ENVIRONMENT EXAMPLE
# ============================================================================
ENV_EXAMPLE = """# Generated by `rilavo init --framework {framework}`
# Copy to .env and fill in your values

# Rilavo Configuration
RILAVO_AUDIENCE=YOUR_AUDIENCE_HERE
RILAVO_ISSUER_KEY_PATH=./issuer_public_key.pem

# Application
PORT={port}
NODE_ENV=development
"""

# ============================================================================
# TEMPLATE REGISTRY
# ============================================================================

# Framework configurations
FRAMEWORK_CONFIGS = {
    "nextjs": {
        "name": "Next.js",
        "port": 3000,
        "base_image": "node:20-alpine",
        "install_deps": "npm ci",
        "build_cmd": "npm run build",
        "copy_artifacts": "COPY --from=builder /app/.next/standalone ./\nCOPY --from=builder /app/public ./public\nCOPY --from=builder /app/node_modules ./node_modules",
        "cmd": "node server.js",
        "install_cmd": "npm install",
        "run_cmd": "npm run dev",
        "dev_cmd": "npm run dev",
        "setup_name": "Node.js",
        "setup_id": "node",
        "setup_version": "20",
        "cache": "npm",
        "test_cmd": "npm test",
        "lint_cmd": "npm run lint",
    },
    "fastapi": {
        "name": "FastAPI",
        "port": 8000,
        "base_image": "python:3.11-slim",
        "install_deps": "pip install -e .",
        "build_cmd": "",
        "copy_artifacts": "COPY --from=builder /app .",
        "cmd": "uvicorn main:app --host 0.0.0.0 --port 8000",
        "install_cmd": "pip install -e .",
        "run_cmd": "uvicorn main:app --reload",
        "dev_cmd": "uvicorn main:app --reload",
        "setup_name": "Python",
        "setup_id": "python",
        "setup_version": "3.11",
        "cache": "pip",
        "test_cmd": "pytest",
        "lint_cmd": "ruff check .",
    },
    "express": {
        "name": "Express.js",
        "port": 3000,
        "base_image": "node:20-alpine",
        "install_deps": "npm ci",
        "build_cmd": "",
        "copy_artifacts": "COPY --from=builder /app .",
        "cmd": "node index.js",
        "install_cmd": "npm install",
        "run_cmd": "npm run dev",
        "dev_cmd": "nodemon index.js",
        "setup_name": "Node.js",
        "setup_id": "node",
        "setup_version": "20",
        "cache": "npm",
        "test_cmd": "npm test",
        "lint_cmd": "npm run lint",
    },
    "go": {
        "name": "Go",
        "port": 8080,
        "base_image": "golang:1.22-alpine",
        "install_deps": "go mod download",
        "build_cmd": "go build -o app .",
        "copy_artifacts": "COPY --from=builder /app/app .",
        "cmd": "./app",
        "install_cmd": "go mod tidy",
        "run_cmd": "go run .",
        "dev_cmd": "air",
        "setup_name": "Go",
        "setup_id": "go",
        "setup_version": "1.22",
        "cache": "go",
        "test_cmd": "go test ./...",
        "lint_cmd": "golangci-lint run",
    },
    "wordpress": {
        "name": "WordPress Plugin",
        "port": 80,
        "base_image": "php:8.2-apache",
        "install_deps": "composer install --no-dev",
        "build_cmd": "",
        "copy_artifacts": "COPY --from=builder /app /var/www/html/wp-content/plugins/rilavo-verification",
        "cmd": "apache2-foreground",
        "install_cmd": "composer install",
        "run_cmd": "N/A (WordPress plugin)",
        "dev_cmd": "N/A (WordPress plugin)",
        "setup_name": "PHP",
        "setup_id": "php",
        "setup_version": "8.2",
        "cache": "composer",
        "test_cmd": "composer test",
        "lint_cmd": "composer cs-check",
    },
}

# Template file maps per framework
TEMPLATE_FILES = {
    "nextjs": {"middleware.ts": NEXTJS_MIDDLEWARE_TS},
    "fastapi": {"main.py": FASTAPI_MAIN_PY},
    "express": {"rilavo-gate.js": EXPRESS_GATE_JS},
    "go": {"main.go": GO_MAIN, "go.mod": GO_GO_MOD},
    "wordpress": {"rilavo-verification.php": WP_PLUGIN, "composer.json": WP_COMPOSER},
}

# Additional files per framework
ADDITIONAL_FILES = {
    "nextjs": ["Dockerfile", "README.md", ".env.example", ".github/workflows/ci.yml", "package.json"],
    "fastapi": ["Dockerfile", "README.md", ".env.example", ".github/workflows/ci.yml"],
    "express": ["Dockerfile", "README.md", ".env.example", ".github/workflows/ci.yml", "package.json"],
    "go": ["Dockerfile", "README.md", ".env.example", ".github/workflows/ci.yml"],
    "wordpress": ["README.md", ".github/workflows/ci.yml"],
}

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def _render(template: str, framework: str, config: dict) -> str:
    """Render a template with framework-specific values."""
    # Remove explicit params from config to avoid duplicates
    config_copy = {k: v for k, v in config.items() if k not in ("framework", "project_name")}
    return template.format(
        framework=framework,
        project_name=config.get("project_name", "my-rilavo-app"),
        **config_copy,
    )

def _generate_dockerfile(framework: str, config: dict) -> str:
    return _render(DOCKERFILE, framework, config)

def _generate_readme(framework: str, config: dict) -> str:
    return _render(README, framework, config)

def _generate_github_ci(framework: str, config: dict) -> str:
    return _render(GITHUB_CI, framework, config)

def _generate_env_example(framework: str, config: dict) -> str:
    return _render(ENV_EXAMPLE, framework, config)

def _generate_package_json(framework: str, config: dict) -> str:
    """Generate package.json for Node.js frameworks."""
    if framework not in ["nextjs", "express"]:
        return ""

    deps = {
        "nextjs": {
            "@rilavo/next": "^0.1.0",
            "@rilavo/sdk": "^0.1.0",
        },
        "express": {
            "@rilavo/sdk": "^0.1.0",
        },
    }

    pkg = {
        "name": config.get("project_name", "my-rilavo-app"),
        "version": "0.1.0",
        "private": True,
        "scripts": {
            "dev": config.get("dev_cmd", ""),
            "build": "next build" if framework == "nextjs" else "",
            "start": "node server.js" if framework == "nextjs" else "node index.js",
            "test": "jest",
            "lint": "eslint .",
        },
        "dependencies": deps.get(framework, {}),
        "devDependencies": {
            "jest": "^29.0.0",
            "eslint": "^8.0.0",
        },
    }

    return json.dumps(pkg, indent=2)

# ============================================================================
# MAIN SCAFFOLD FUNCTION
# ============================================================================

TEMPLATES = {
    "nextjs": {"middleware.ts": NEXTJS_MIDDLEWARE_TS},
    "fastapi": {"main.py": FASTAPI_MAIN_PY},
    "express": {"rilavo-gate.js": EXPRESS_GATE_JS},
    "go": {"main.go": GO_MAIN, "go.mod": GO_GO_MOD},
    "wordpress": {"rilavo-verification.php": WP_PLUGIN, "composer.json": WP_COMPOSER},
}

FRAMEWORKS = tuple(TEMPLATES.keys())

def scaffold(framework: str, target_dir: str | Path, project_name: str = "my-rilavo-app") -> list[Path]:
    """Write the framework template files into target_dir. Returns paths."""
    if framework not in TEMPLATES:
        raise ValueError(f"unknown framework {framework!r}; choose from {list(FRAMEWORKS)}")

    target = Path(target_dir)
    target.mkdir(parents=True, exist_ok=True)

    config = {
        "framework": framework,
        "project_name": project_name,
        **FRAMEWORK_CONFIGS[framework],
    }

    written: list[Path] = []

    # Core template files
    for name, body in TEMPLATES[framework].items():
        path = target / name
        if path.exists():
            raise FileExistsError(f"refusing to overwrite existing file: {path}")
        path.write_text(body, encoding="utf-8")
        written.append(path)

    # Additional files
    for filename in ADDITIONAL_FILES.get(framework, []):
        path = target / filename
        if path.exists():
            continue  # Skip if already exists

        if filename == "Dockerfile":
            content = _generate_dockerfile(framework, config)
        elif filename == "README.md":
            content = _generate_readme(framework, config)
        elif filename == ".env.example":
            content = _generate_env_example(framework, config)
        elif filename == ".github/workflows/ci.yml":
            content = _generate_github_ci(framework, config)
        elif filename == "package.json":
            content = _generate_package_json(framework, config)
        else:
            continue

        if content:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            written.append(path)

    return written

# Framework list for CLI
FRAMEWORKS = tuple(TEMPLATES.keys())
