// Generated by `rilavo init --framework go`.
// Fail-closed Rilavo gate for Go net/http (P2-B4). Requires:
//   go get github.com/rilavo/rilavo-go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/rilavo/rilavo-go"
)

func main() {
	// Trust source: configure with your issuer directory and revocation log.
	directory := rilavo.NewKeyDirectory()
	// directory.Publish(...)  // Add your issuer key entry

	revLog := &rilavo.RevocationLog{}
	nonceCache := rilavo.NewNonceCache()

	verifier := rilavo.NewVerifier(directory, revLog, nonceCache)

	// Middleware
	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		fmt.Fprintln(w, `{"message": "Access granted"}`)
	})

	// Wrap with Rilavo gate
	gated := rilavo.Middleware(verifier, "YOUR_AUDIENCE_HERE")(handler)

	http.Handle("/protected", gated)
	http.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintln(w, `{"status": "ok"}`)
	})

	log.Fatal(http.ListenAndServe(":8080", nil))
}
