#!/usr/bin/env python3
"""Self-hosted issuance server (P-31 path 2 / P-32 checklist).

Runs the protocol's HTTP service under YOUR OWN key generated by
`rilavo keygen` -- zero dependency on anyone else's infrastructure.

Usage:
    uv run python deploy/selfhosted/server.py --key issuer.pem --port 8090
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from rilavo.api import Issuer
from rilavo.service import RilavoService


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--key", required=True, help="private key PEM from 'rilavo keygen'")
    ap.add_argument("--port", type=int, default=8090)
    args = ap.parse_args()

    key = serialization.load_pem_private_key(Path(args.key).read_bytes(), password=None)
    if not isinstance(key, Ed25519PrivateKey):
        raise SystemExit("not an Ed25519 private key")

    service = RilavoService(port=args.port, issuer=Issuer(private_key=key)).start()
    print(f"self-hosted issuer live on {service.url}", flush=True)
    print("directory entry:", flush=True)
    entry = service.state.issuer.directory_entry()
    print(json.dumps({"issuer_id": entry.fingerprint_id,
                      "public_key_pem": entry.public_key_pem.decode(),
                      "valid_until": entry.valid_until}, indent=2))
    import threading
    threading.Event().wait()      # serve until Ctrl-C


if __name__ == "__main__":
    main()
