# Generated by `rilavo init --framework fastapi`.
# Fail-closed Rilavo gate for FastAPI (P2-B2). Requires:
#   pip install fastapi uvicorn  (rilavo already installed)
from fastapi import Depends, FastAPI

from rilavo.fastapi import require_rilavo_agent
from rilavo.keys import IssuerKeyEntry, KeyDirectory

app = FastAPI()

# Trust source: point this at your issuer directory (static here; swap in
# DiscoveringKeyDirectory for .well-known/rilavo discovery).
directory = KeyDirectory()
directory.publish(IssuerKeyEntry(
    fingerprint_id="rilavo:iss:YOUR_ISSUER_ID",
    public_key_pem=open("issuer_public_key.pem", "rb").read(),
    valid_until=9999999999.0,
))

# Gate order matches verifier.py exactly:
# version -> expiry -> audience -> delegation -> signature -> PoP.
agent = require_rilavo_agent(
    audience="YOUR_AUDIENCE_HERE",
    key_directory=directory,
)


@app.get("/protected")
async def protected(result: dict = Depends(agent)):
    # Raises HTTPException 401 with reason_code on failure.
    return {"message": "Access granted", "principal": result.principal}
