// Generated by `rilavo init --framework nextjs`.
// Fail-closed Rilavo gate for Next.js (P2-A). Requires:
//   npm install @rilavo/sdk @rilavo/next
import { createMiddleware } from '@rilavo/next';

const withRilavo = createMiddleware({
  audience: 'YOUR_AUDIENCE_HERE',
  publicPaths: ['/', '/public/:path*'],
  // Wire issuerDirectory / revocationLog to your trust sources here.
});

export default withRilavo;

export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon.ico).*)'],
};
