// Generated by `rilavo init --framework express`.
// Fail-closed Rilavo gate for Express/Connect (P2-B3). Requires:
//   npm install @rilavo/sdk
const { verifyCredential, NonceCache } = require('@rilavo/sdk');

const HEADER = 'x-rilavo-credential';
const AUDIENCE = 'YOUR_AUDIENCE_HERE';

// Trust source: configure with your issuer directory and revocation log.
const issuerDirectory = {
  unreachable: false,
  lookup(issuerId) {
    // TODO: Implement issuer directory lookup.
    // Must resolve issuerId to {issuerId: string, publicKeyPem: string, validUntil: int}.
    // Options: static in-memory map, filesystem, HTTP discovery (RILAVO_ISSUER_DIR_URL),
    // or external key management service. Return null on unknown/not found (fail-closed).
    return null;
  },
};
const revocationLog = { isRevoked: () => false };
const nonceCache = new NonceCache();   // process-wide replay cache

function rilavoGate(req, res, next) {
  const raw = req.get(HEADER);
  if (!raw) return res.status(401).json({ error: 'no_credentials' });

  let fields;
  try {
    fields = JSON.parse(Buffer.from(raw, 'base64').toString('utf8'));
  } catch {
    return res.status(401).json({ error: 'malformed_credential' });
  }

  const result = verifyCredential(
    fields,
    {
      method: req.method,
      path: req.path,
      requestedAction: req.get('x-rilavo-action') || '',
      signature: req.get('x-rilavo-pop-signature') || '',
      requestNonce: req.get('x-rilavo-request-nonce') || '',
    },
    {
      issuerDirectory,
      revocationLog,
      nonceCache,
      verifierAudience: AUDIENCE,
    },
  );

  if (!result.accepted) {
    return res.status(401).json({ error: result.reasonCode });
  }
  req.rilavo = result;
  next();
}

module.exports = { rilavoGate };
